[server]
bind = "127.0.0.1"
port = 8080

[app]
session_key = "1X3wtCdb9qkpWg3aX0BCaN1JFho8W/77g1SF76S1SEI="

[auth]
client_id = "**********"
client_secret = "****************"
token_signing_key = "WU9VUiBUT0tFTiBTSUdOSU5HIEtFWQ=="

[database]
host = "localhost"
port = 5432
database = "actixexp"
user = "actixexp"
password = "***********"

[frontend]
base_uri = "http://localhost:3000"
