version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    entrypoint:
      - actixexp
      - --bind=0.0.0.0
      - --port=8000
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=actixexp
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
